name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y poppler-utils
      - name: Install Python dependencies
        run: pip install Pillow pdf2image pytest
      - name: Run tests
        run: pytest -q
